# Site
title:              'simoexpo.dev'
description:        'Just some random thoughts'
locale:             'en_US'
version:            '0.1'

# Author
author:             
  name:             'Simone Esposito'
  role:             'Software developer'
  company:          'Bitrock'
  cv:               ''   
  github:             
    url:            'https://github.com/simoexpo'
    name:           'simoexpo'
  linkedin:         'https://www.linkedin.com/in/simoneesposito90/'
  twitter:          'https://twitter.com/simoexpo90'

# Jekyll
sass:
  sass_dir:         '_sass'
  style:            'compressed'

assets:
  sources:
                    - assets/images
